### ISSUE TITLE
速度药水过后玩家移动速度不正常

### ISSUE THREAD

**Issue by Nissining** [MemoriesOfTime/Nukkit-MOT#22]
如题，速度药水过后玩家貌似无法疾跑或者其他原因
明显的速度不正常

**Comment by glorydark** [comment]
经测试，**疾跑效果结束时，如果玩家正在冲刺，玩家的移动速度都将会恢复到0.1f（而正常疾跑状态下应该是0.13f）**，从而造成阻停现象（就像是取消了玩家的疾跑状态，其实并未取消）。**但玩家仍可通过再次开启疾跑恢复正常。**

From the test, it is obvious that player sprinting possess a wrong speed(0.1f) after the SPEED potion effect has expired. Despite that, the speed will return to the normal level when players stop sprinting and then sprint again.

``` yaml
# References
Normal speed: 0.1
Normal speed while sprinting: 0.1*1.3 = 0.13
```
